USE [master]
GO

/****** Object:  Database [CC]    Script Date: 17/04/2016 16:40:02 ******/
CREATE DATABASE [CC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CC', FILENAME = N'E:\Data\CC.mdf' , SIZE = 36340992KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'CC_log', FILENAME = N'E:\Logs\CC_log.LDF' , SIZE = 34605184KB , MAXSIZE = 2048GB , FILEGROWTH = 131072KB )
GO

ALTER DATABASE [CC] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CC] SET ARITHABORT OFF 
GO

ALTER DATABASE [CC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CC] SET RECOVERY FULL 
GO

ALTER DATABASE [CC] SET  MULTI_USER 
GO

ALTER DATABASE [CC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CC] SET  READ_WRITE 
GO


