SELECT DISTINCT CONTACT.Contact_ID ID , CONTACT.Contact_Reference,
 CONTACT.Current_Group_Id, CONTACT.Current_Owner_Id, 
 CONTACT.Contact_Method_Id, CONTACT.Contact_Priority_Id,
  CONTACT.Contact_Status_Id, party.Description,
   CONTACT.Created, UNKNOWN_X.D001, CONTACT_PART_X.L001,
    CONTACT_PART_X.L002, CONTACT_PART_X.L003, CONTACT_PART_X.L004,
	 CONTACT_PART_X.L19, CONTACT_PART_X.L20, CONTACT_PART_X.L21, 
	 CONTACT_PART_X.L22,CONTACT_PART_X.L23, CONTACT_PART_X.L24,
	  CONTACT_PART_X.L25, CONTACT_PART_X.L26,CONTACT_PART_X.L007,
	   CONTACT_PART_X.L008, CONTACT_PART_X.L009, CONTACT_PART_X.L010,
	    CONTACT_PART_X.L27, CONTACT_PART_X.L28, CONTACT_PART_X.L29,
		 CONTACT_PART_X.L30,CONTACT_PART_X.L31, CONTACT_PART_X.L32,
		  CONTACT_PART_X.L33, CONTACT_PART_X.L34,U2.Last_Name + ' (Regarding)' sourcetype 
FROM CONTACT_PART_X, CONTACT_PART, CONTACT, CONTACT_SOURCE,
 PARTY, UNKNOWN_X, CONTACT_PART_X CPX2, UNKNOWN U2
WHERE CONTACT.Contact_Id = CONTACT_PART_X.Contact_Id
  AND CONTACT_PART_X.Contact_Part_Id = CONTACT_PART.Contact_Part_Id
  AND CONTACT_PART.Primary_Flag = 1
  AND CONTACT_SOURCE.Contact_Id = CONTACT.Contact_Id
  AND Party.Party_Id = UNKNOWN_X.Party_Id
    AND CONTACT_SOURCE.Primary_Flag = 1
  AND CONTACT_SOURCE.Party_Id = PARTY.Party_Id
  AND CONTACT.Contact_Id = CPX2.Contact_Id
  AND CPX2.L006 = U2.Party_Id     
  AND (( CONTACT.Contact_Status_Id <> 3		
  AND CONTACT.Status_Type = 1)		
OR
(CONTACT.CREATED >= CONVERT(DATETIME, '2014-03-16', 102) 
AND CONTACT.CREATED <= CONVERT(DATETIME, '2016-03-16', 102)))

  ORDER BY ID  