select
			P.*,
			U.Reference				as U_Reference,
			U.Company				as U_Company,
			U.UC_Company			as U_UC_Company,
			U.Address				as U_Address,
			U.Town				as U_Town,
			U.County				as U_County,
			U.Country				as U_Country,
			U.Postcode				as U_Postcode,
			U.Title				as U_Title,
			U.First_Name			as U_First_Name,
			U.Last_Name				as U_Last_Name,
			U.UC_Last_Name			as U_UC_Last_Name,
			U.SX_Last_Name			as U_SX_Last_Name,
			U.Blocked				as U_Blocked,
			U.PFE_1				as U_PFE_1,
			U.PFE_2				as U_PFE_2,
			U.PFE_3				as U_PFE_3,
			null					as K_Reference,
			null					as K_Company_Department,
			null					as K_UC_Company_Department,
			null					as K_Address,
			null					as K_Town,
			null					as K_County,
			null					as K_Country,
			null					as K_Postcode,
			null					as K_PFE_1,
			null					as K_PFE_2,
			null					as K_PFE_3,
			 (null)			as K_Grid_Ref_Long,
			 (null)			as K_Grid_Ref_Lat
	From
			Party P,
			Unknown U
	Where
			P.Party_Id = U.Party_Id
union all
	select
			P.*,
			null					as U_Reference,
			null					as U_Company,
			null					as U_UC_Company,
			null					as U_Address,
			null					as U_Town,
			null					as U_County,
			null					as U_Country,
			null					as U_Postcode,
			null					as U_Title,
			null					as U_First_Name,
			null					as U_Last_Name,
			null					as U_UC_Last_Name,
			null					as U_SX_Last_Name,
			 (null)			as U_Blocked,
			null					as U_PFE_1,
			null					as U_PFE_2,
			null					as U_PFE_3,
			K.Reference				as K_Reference,
			K.Company_Department		as K_Company_Department,
			K.UC_Company_Department		as K_UC_Company_Department,
			K.Address				as K_Address,
			K.Town				as K_Town,
			K.County				as K_County,
			K.Country				as K_Country,
			K.Postcode				as K_Postcode,
			K.PFE_1				as K_PFE_1,
			K.PFE_2				as K_PFE_2,
			K.PFE_3				as K_PFE_3,
			K.Grid_Ref_Long			as K_Grid_Ref_Long,
			K.Grid_Ref_Lat			as K_Grid_Ref_Lat
	From
			Party P,
			Known K
	Where
			P.Party_Id = K.Party_Id
union all
	select
			P.*,
			null					as U_Reference,
			null					as U_Company,
			null					as U_UC_Company,
			null					as U_Address,
			null					as U_Town,
			null					as U_County,
			null					as U_Country,
			null					as U_Postcode,
			null					as U_Title,
			null					as U_First_Name,
			null					as U_Last_Name,
			null					as U_UC_Last_Name,
			null					as U_SX_Last_Name,
			 (null)			as U_Blocked,
			null					as U_PFE_1,
			null					as U_PFE_2,
			null					as U_PFE_3,
			null					as K_Reference,
			null					as K_Company_Department,
			null					as K_UC_Company_Department,
			null					as K_Address,
			null					as K_Town,
			null					as K_County,
			null					as K_Country,
			null					as K_Postcode,
			null					as K_PFE_1,
			null					as K_PFE_2,
			null					as K_PFE_3,
			 (null)			as K_Grid_Ref_Long,
			 (null)			as K_Grid_Ref_Lat
	From
			Party P
	Where
			P.Party_Id = 1